### PR TITLE
fix: Avoid implicit join when using join with unnest

### LINKED ISSUE #368: Unnest Function In BigQuery SQLAlchemy Plugin Joins Twice When Selecting Other Columns in CTE or Subquery
From a customer support request:

**Issue summary**: This issue is closely related to [Unnest function in BigQuery SQLAlchemy plugin joins twice when selecting other columns #353](https://github.com/googleapis/python-bigquery-sqlalchemy/issues/353). After the previous issue was resolved, queries using the UNNEST function that are not in Common Table Expressions (CTE) or subqueries work as expected. See the following minimal example:

```
from sqlalchemy import create_engine, MetaData, select, func as F, Table, Column, Integer, ARRAY

metadata = MetaData()
table = Table(
  "table1",
  metadata,
  Column("foo", Integer),
  Column("bars", ARRAY(Integer))
)

engine = create_engine("bigquery://", future=True)
q = select(table.c.foo, F.unnest(table.c.bars).column_valued("bar"))
print(q.compile(engine))
```

This outputs the following, which is expected:
```
SELECT `table1`.`foo`, `bar` 
FROM `table1`, unnest(`table1`.`bars`) AS `bar`
```

However, if we use the table as a subquery or CTE, the issue manifests again. The following code (continuing from above):

```
q = q.cte("cte")
q = select(*q.columns)
print(q.compile(engine))
```

Produces the next output:

```
WITH `cte` AS 
(SELECT `table1`.`foo` AS `foo`, `bar` 
FROM `table1`, `table1` `table1_1`, unnest(`table1_1`.`bars`) AS `bar`)
 SELECT `cte`.`foo`, `cte`.`bar` 
FROM `cte`
```
Note that `table1` is duplicated in the `FROM` clause again.

**Expected behavior**: It is expected to generate the following query instead (note the different FROM clause):
```
WITH `cte` AS 
(SELECT `table1`.`foo`, `bar` 
FROM `table1`, unnest(`table1`.`bars`) AS `bar`)
 SELECT `cte`.`foo`, `cte`.`bar` 
FROM `cte`
```

### PR DESCRIPTION
**Pull request by snapiri**
When using JOIN with UNNEST statements, and then creating a SELECT statement based on it, the UNNESTed table will appear twice in the FROM clause, causing an implicit join of the table with itself

Sample of problematic code:
```
from sqlalchemy import ARRAY, Column, create_engine, func, Integer, MetaData, Table, column, select

db_metadata = MetaData()
engine = create_engine("bigquery://", future=True)

column_defs1 = [Column("id", Integer, nullable=True)]
column_defs2 = [Column("ids", ARRAY(Integer), nullable=True), Column("dummy", Integer, nullable=True)]

table1 = Table("table1", db_metadata, *column_defs1)
table2 = Table("table2", db_metadata, *column_defs2)

unnested_col_name = "unnested_ids"
unnested_ids = func.unnest(table2.c.ids).alias(unnested_col_name)
unnested_id_col = column(unnested_col_name)

q = select(table1.c.id, table2.c.dummy).select_from(unnested_ids.join(table1, table1.c.id == unnested_id_col))

# This is where things go bad
q = select("*").select_from(q.subquery())
compiled = q.compile(engine)
print(str(compiled))
```
Generates the following output:
```
SELECT *
FROM (SELECT `table1`.`id` AS `id`, `table2`.`dummy` AS `dummy`
FROM `table2`, `table2` `table2_1`, unnest(`table2_1`.`ids`) AS `unnested_ids` JOIN `table1` ON `table1`.`id` = `unnested_ids`) AS `anon_1`
```

Co-Authored-By: @yuval-bavli

Fixes #368

### CODE REVIEW

**Comment by snapiri** [comment]
@tswast Would appreciate your review if possible.

**Comment by snapiri** [comment]
@chalmerlowe / @Linchin,
kind reminder - could you please review?

**Comment by snapiri** [comment]
Seems like the `kokoro` test is failing on some unrelated permissions error.
Can anyone take a look or advise?
```
Traceback (most recent call last):
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/tests/system/test_sqlalchemy_bigquery.py", line 348, in test_tables_list
    tables = engine.table_names()
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2317, in table_names
    return self.dialect.get_table_names(conn, schema)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/sqlalchemy_bigquery/base.py", line 1033, in get_table_names
    return self._get_table_or_view_names(connection, item_types, schema)
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/sqlalchemy_bigquery/base.py", line 878, in _get_table_or_view_names
    for table in tables:
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/page_iterator.py", line 208, in _items_iter
    for page in self._page_iter(increment=False):
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/page_iterator.py", line 244, in _page_iter
    page = self._next_page()
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/page_iterator.py", line 373, in _next_page
    response = self._get_next_page_response()
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/page_iterator.py", line 432, in _get_next_page_response
    return self.api_request(
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 1551, in api_request
    return self._call_api(
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 808, in _call_api
    return call()
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/tmpfs/src/github/python-bigquery-sqlalchemy/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://bigquery.googleapis.com/bigquery/v2/projects/precise-truck-742/datasets/python_bigquery_tests_system_load_gcs_then_dump_1701976995793/tables?maxResults=1000&prettyPrint=false: Access Denied: Dataset precise-truck-742:python_bigquery_tests_system_load_gcs_then_dump_1701976995793: Permission bigquery.tables.list denied on dataset precise-truck-742:python_bigquery_tests_system_load_gcs_then_dump_1701976995793 (or it may not exist).
```

**Comment by Linchin** [comment]
Hi @snapiri, cover test is also failing
```
nox > coverage report --show-missing --fail-under=100
Name                                     Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------------------
sqlalchemy_bigquery/__init__.py             12      0      0      0   100%
sqlalchemy_bigquery/_helpers.py             43      0     14      0   100%
sqlalchemy_bigquery/_struct.py              47      0     16      0   100%
sqlalchemy_bigquery/_types.py               53      0     18      0   100%
sqlalchemy_bigquery/base.py                497      0    152      2    99%   275->281, 276->281
sqlalchemy_bigquery/geography.py            51      0     14      0   100%
sqlalchemy_bigquery/parse_url.py           125      0     56      0   100%
sqlalchemy_bigquery/version.py               1      0      0      0   100%
tests/unit/__init__.py                       0      0      0      0   100%
tests/unit/conftest.py                      49      0      4      0   100%
tests/unit/fauxdbi.py                      214      0     70      0   100%
tests/unit/test__struct.py                  33      0      0      0   100%
tests/unit/test_catalog_functions.py        77      0      6      0   100%
tests/unit/test_comments.py                 28      0      0      0   100%
tests/unit/test_compiler.py                 68      0      0      0   100%
tests/unit/test_compliance.py               61      0      8      0   100%
tests/unit/test_dialect_types.py             7      0      2      0   100%
tests/unit/test_engine.py                   30      0      0      0   100%
tests/unit/test_geography.py                58      0      0      0   100%
tests/unit/test_helpers.py                  94      0      0      0   100%
tests/unit/test_like_reescape.py            17      0      0      0   100%
tests/unit/test_parse_url.py                90      0     10      0   100%
tests/unit/test_select.py                  157      0     22      0   100%
tests/unit/test_sqlalchemy_bigquery.py      76      0      4      0   100%
tests/unit/test_version.py                   6      0      0      0   100%
tests/unit/test_view.py                      7      0      0      0   100%
------------------------------------------------------------------------------------
TOTAL                                     1901      0    396      2    99%
Coverage failure: total of 99 is less than fail-under=100
```

**Comment by snapiri** [comment]
@Linchin fixed cover and added more tests.
Would appreciate any feedback

**Comment by snapiri** [comment]
@tswast / @Linchin / @chalmerlowe 
Anyone care to review?

**Comment by snapiri** [comment]
@tswast - Not sure I know how to read the `Kokoro` results - I see that the `system-3.8` tests failed with the following error:
```
google.api_core.exceptions.ServiceUnavailable: 503 GET https://bigquery.googleapis.com/bigquery/v2/projects/precise-truck-742/jobs/72b3d73c-939c-4d7f-ab50-06f073ecac58?location=US&prettyPrint=false: The service is currently unavailable.
```
Also I see that there were 6 runs where the first failed and the 2-6 succeeded.

Anything I should change?

**Comment by tswast** [comment]
@snapiri That looks like a backend issue, not anything related to this code. I'll trigger a re-run.

**Review by tswast — APPROVED** [review]

**Pull request merged**
