### PR TITLE
feat: add support for SQLAlchemy 1.4

### PR DESCRIPTION
**Pull request by alonme**
Still a draft, need to make sure all this changes will not break users in older versions of SQLA

### CODE REVIEW

**Comment by alonme** [comment]
closes #83

**Comment by tswast** [comment]
Thanks! Let me know once this is ready for review.

**Comment by alonme** [comment]
@tswast - Almost ready, 
I'm debating about having SQLA 1.4 a dev requirement (for tests)
and about 1 issue of backward compatibility, which might be an issue only if someone actually passed `inline` to `BigQueryCompiler`

**Comment by tswast** [comment]
> I'm debating about having SQLA 1.4 a dev requirement (for tests)

Ideally we'd have some test sessions for our minimum requirements as well as the latest supported. I've created https://github.com/mxmzdlv/pybigquery/issues/85 to track this.

**Comment by tswast** [comment]
In the meantime, I'm okay adding a dev requirement.

**Comment by tswast** [comment]
@alonme Apologies, but I just "blackened" all the source in this repo. It will most likely cause some conflicts.

In good news, we do now have "constraints" files in the `testing/` directory which allow us to test against specific package versions for each of our test sessions. Plain ol' pytest should still work, but to use that multi-version testing, we can run with `nox` http://nox.thea.codes/

**Comment by jimfulton** [comment]
See: #177

**Pull request closed without merging**
