### PR TITLE
fix: remove "future" dependency

### LINKED ISSUE #541: remove dependency on "future"
**Is your feature request related to a problem? Please describe.**

https://github.com/PythonCharmers/python-future/issues/612
there is a CVE against this dependency. the project does not actually need the dependency (python2 is not supported by the library anyway)

 **Describe the solution you'd like**

remove the dependency, cleaning up is good

 **Describe alternatives you've considered**

can wait for the CVE to be fixed. (and maybe another one to appear later)

### PR DESCRIPTION
**Pull request by domsj**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-sqlalchemy/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes https://github.com/googleapis/python-bigquery-sqlalchemy/issues/541 🦕

### CODE REVIEW

**Comment by domsj** [comment]
ping

**Comment by Giuzzilla** [comment]
@domsj While you wait for the contributors to review this, I suggest rebasing against main (should fix the failing tests)

**Comment by domsj** [comment]
guys, just merge it already

**Comment by meredithslota** [comment]
Hi @domsj — thank you so much for submitting. We've had some team changes recently and are figuring out how to regroup, apologies for the delay here. I appreciate the contribution!

**Comment by domsj** [comment]
@chalmerlowe @parthea please approve & merge

**Comment by chalmerlowe** [comment]
@domsj 
I will try to look this over today. Waiting on the tests to pass.

**Comment by domsj** [comment]
> @domsj I will try to look this over today. Waiting on the tests to pass.

@chalmerlowe I think you (or someone else) needs to (re-)approve running the tests. They succeeded before, but need to run again after I merged in latest master (because there was a conflict in the meantime)

**Review by chalmerlowe — APPROVED** [review]
LGTM. Approval

**Comment by chalmerlowe** [comment]
Thanks @domsj. Appreciate the help.

**Pull request merged**
