### PR TITLE
fix: updates test to account for UTC in failing test

### PR DESCRIPTION
**Pull request by chalmerlowe**
Some of the tests were not passing following the submission of #499 so this PR is being issued as part of helping to fix issue #385 🦕

### CODE REVIEW

**Comment by chalmerlowe** [comment]
The failure in the kokoro **Prerelease** test is a known issue and will be corrected in a PR for the Google python-bigquery library: https://github.com/googleapis/python-bigquery/issues/1376

This PR is expected to be merged into python-bigquery in [release 3.3.6](https://github.com/googleapis/python-bigquery/pull/1375).

**Comment by chalmerlowe** [comment]
20221104: there is a prerelease issue with parsing the sqlalchemy version number.
The prerelease version number is x.x.0b2.
The patch value of 0b2 cannot be converted to an integer and thus the prerelease test fails.

**Comment by chalmerlowe** [comment]
@parthea can you approve and merge. See my comment above about the patch version number, which is a transient issue and should not interfere with the functionality of this PR.

**Review by parthea — APPROVED** [review]

**Comment by parthea** [comment]
Merge #499 first

**Pull request merged**
