### PR TITLE
fix: implement modulus operator

### PR DESCRIPTION
**Pull request by aholyoke**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-sqlalchemy/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

---
Adds implementation of mod operator `%`

Currently if I try to use `%` in python code, it will fall back to the SA default compiler implementation which renders it as a percent sign, which is not syntactically valid in BQ. I could workaround this by using `func.mod`, but this isn't portable across dialects (eg. SQL Server has support for `%`, but not `MOD`)

### CODE REVIEW

**Comment by aholyoke** [comment]
@Linchin This seems like a pretty safe change. Any chance you can review it?

**Comment by chalmerlowe** [comment]
@aholyoke 

Can you do me a favor?
Can you provide me with a example of what the outcome would look like if used *in situ* (not the fake version generated by the test code) but a sample that includes the calculation of a modulo compared to zero for example:

The sqlalchemy commands that would generate a statement that includes something akin to `blah, blah, blah MOD(X, Y) == 0`

I want to ensure that I am picturing this the way you are.

Thanks.

**Comment by aholyoke** [comment]
@chalmerlowe Sure, this is how it behaves before the change
```python
In [1]: import sqlalchemy as sa; from sqlalchemy_bigquery import BigQueryDialect

In [2]: meta = sa.MetaData(); table = sa.Table("table_name", meta, sa.Column("col_name", sa.Integer()))

In [3]: print(str(sa.select(table.c.col_name).where(table.c.col_name % 2 == 0).compile(dialect=BigQueryDialect())))
SELECT `table_name`.`col_name`
FROM `table_name`
WHERE `table_name`.`col_name` % :col_name_1 = :param_1
```
Which the following screenshots confirm is not the correct syntax in BQ:
Screenshot 2024-06-30 at 9 58 36 PM
Screenshot 2024-06-30 at 9 58 53 PM


and this is how it behaves after the change
```python
In [1]: import sqlalchemy as sa; from sqlalchemy_bigquery import BigQueryDialect

In [2]: meta = sa.MetaData(); table = sa.Table("table_name", meta, sa.Column("col_name", sa.Integer()))

In [3]: print(str(sa.select(table.c.col_name).where(table.c.col_name % 2 == 0).compile(dialect=BigQueryDialect())))
SELECT `table_name`.`col_name`
FROM `table_name`
WHERE MOD(`table_name`.`col_name`, :col_name_1) = :param_1

In [4]: sa.select(table.c.col_name).where(table.c.col_name % 2 == 0).compile(dialect=BigQueryDialect()).params
Out[4]: {'col_name_1': 2, 'param_1': 0}
```

**Review by chalmerlowe — APPROVED** [review]
LGTM.

**Comment by chalmerlowe** [comment]
@aholyoke 

Thanks for pushing this PR. We appreciate the effort and your support in better understanding the nature of the issue this solves. 

Have a great day! 💜

**Pull request merged**
